### ISSUE TITLE
Maxent.jar location

### ISSUE THREAD

**Issue by cvisintin** [qaecology/boab#3]
https://github.com/qaecology/boab/blob/7baf111575d9622d3a35f587b0cc98748b23d7c9/Dockerfile#L189-L190

The maxent file has to be manually moved to the dismo installation directory...I am having trouble knowing where that is in the image. Should it be moved in the user creation script?

**Comment by goldingn** [comment]
Try this:

```
RUN R -e 'install.packages(c("dismo"))' 
RUN R -e 'file.copy("Maxent/maxent.jar", file.path(system.file(package = "dismo"), "java/maxent.jar"))'
```

**Comment by jdyen** [comment]
Yep, that worked. Just needed to copy from `/opt/Maxent` (the local copy of Maxent).
