### ISSUE TITLE
greta mcmc and opt do not work on boab image

### ISSUE THREAD

**Issue by jdyen** [qaecology/boab#5]
@goldingn this might be one to handball your way.

Model build came with a heap of warnings about deprecated names, e.g.,
`The name tf.placeholder is deprecated. Please use tf.compat.v1.placeholder instead.`
There were several others.

Then sampling errored:
```
mcmc(model(normal(0, 1)))
```
`running 4 chains simultaneously on up to 72 cores
    warmup                                           0/1000 | eta:  ?s`
`Error in dim(free_state_draws) <- c(1, dim(free_state_draws)) :  invalid first argument`

as did opt (but this one looks a bit easier to fix):
```
 opt(model(normal(0, 1)))
```
`ModuleNotFoundError: No module named 'scipy'`

Installation seemed to go OK, and there weren't any issues with py/tf versions.

**Comment by goldingn** [comment]
I think this just needs the version of greta from github again - I updated it a couple of times in the last few days to work with the latest versions of TF and TFP. So maybe just rebuild the image?

Yeah, the last one just needs scipy installed.

**Comment by jdyen** [comment]
Thanks. Fixed mcmc with install from github instead of CRAN.

I've added scipy install to the dockerfile, opt now works fine.

**Comment by cvisintin** [comment]
Thanks Jian.
